"""Online deployment entrypoint for RAYMOND v2.8."""

from datetime import datetime, timezone

from app.main import app
from app.online_market_api import (
    router as online_market_router,
    _fetch_price,
)
from app.advisory_api import router as advisory_analysis_router
from app.paper_position_management_api import (
    router as paper_position_management_router,
)
from app.paper_position_market_loop import (
    PaperPositionMarketLoop,
    PaperPositionMarketLoopConfig,
)
from app.database import SessionLocal


# ---------------------------------------------------------------------------
# ROUTERS
# ---------------------------------------------------------------------------

# Online public market-data and analysis routes.
app.include_router(online_market_router)

# Stage 16.4:
# 8-brain advisory comparison API.
app.include_router(advisory_analysis_router)

# Stage 17.2:
# Persistent paper-position management API.
#
# SAFETY:
# - Paper positions only.
# - No broker orders.
# - No MT5 execution.
# - Live trading remains disabled.
app.include_router(paper_position_management_router)


# ---------------------------------------------------------------------------
# STAGE 17.3.2
# AUTOMATIC PAPER POSITION MARKET LOOP
# ---------------------------------------------------------------------------

_paper_market_loop = None
_paper_market_loop_db = None


async def _paper_market_price_provider(symbol: str) -> float:
    """
    Supply the automatic paper-position manager with the
    latest public market price.

    This uses the existing read-only online market feed.

    SAFETY:
    - Public market data only.
    - No broker connection.
    - No MT5 execution.
    - No live trading.
    """

    market_data = await _fetch_price(symbol)

    price = market_data.get("price")

    if price is None:
        raise RuntimeError(
            "Online market feed returned no usable price"
        )

    return float(price)


@app.on_event("startup")
async def start_paper_position_market_loop():
    """
    Start the automatic paper-position management loop.

    The worker polls the existing public XAUUSD feed and
    sends the price into PaperPositionManager.

    No broker order can be generated by this worker.
    """

    global _paper_market_loop
    global _paper_market_loop_db

    config = PaperPositionMarketLoopConfig.from_values(
        symbol="XAUUSD",
        interval_seconds=30.0,
        enabled=True,
    )

    _paper_market_loop_db = SessionLocal()

    _paper_market_loop = PaperPositionMarketLoop(
        db=_paper_market_loop_db,
        price_provider=_paper_market_price_provider,
        config=config,
    )

    started = _paper_market_loop.start()

    if started:
        print(
            "RAYMOND Stage 17.3.2: "
            "paper-position market loop started "
            "(XAUUSD / 30s / PAPER ONLY)"
        )
    else:
        print(
            "RAYMOND Stage 17.3.2: "
            "paper-position market loop was not started"
        )


@app.on_event("shutdown")
async def stop_paper_position_market_loop():
    """
    Stop the automatic paper-position management loop cleanly.
    """

    global _paper_market_loop
    global _paper_market_loop_db

    if _paper_market_loop is not None:
        await _paper_market_loop.stop()
        _paper_market_loop = None

    if _paper_market_loop_db is not None:
        _paper_market_loop_db.close()
        _paper_market_loop_db = None

    print(
        "RAYMOND Stage 17.3.2: "
        "paper-position market loop stopped"
    )


# ---------------------------------------------------------------------------
# HEALTH
# ---------------------------------------------------------------------------

@app.get("/health", tags=["Health"])
async def health():
    """Lightweight health check for Render."""

    return {
        "status": "healthy",
        "service": "raymond-v2-8-trader",
        "timestamp": datetime.now(timezone.utc).isoformat(),

        # ---------------------------------------------------------------
        # SAFETY LOCK — LIVE TRADING REMAINS DISABLED.
        # ---------------------------------------------------------------
        "live_trading_enabled": False,

        "paper_trading_enabled": True,

        "paper_position_market_loop": {
            "enabled": True,
            "running": (
                _paper_market_loop.running
                if _paper_market_loop is not None
                else False
            ),
            "symbol": "XAUUSD",
            "interval_seconds": 30.0,
        },

        "safety": {
            "paper_only": True,
            "read_only": True,
            "execution_authorized": False,
            "broker_orders_allowed": False,
            "mt5_execution_allowed": False,
            "risk_engine_bypass": False,
        },
    }
