"""
RAYMOND V2.8 - V5 OPTIMIZER
============================

STEP 2 OF V5 RESEARCH ARCHITECTURE

Purpose
-------
Research-only optimizer for the V5 multi-strategy engine.

This optimizer is deliberately separated from V4.

It evaluates strategy families and parameter combinations using:
    - compounded return
    - profit factor
    - expectancy
    - maximum drawdown
    - consistency
    - trade count
    - yearly performance
    - walk-forward stability

IMPORTANT
---------
This file does NOT:
    - connect to MT5
    - connect to Exness
    - place broker orders
    - modify broker positions
    - enable live trading

The optimizer is a research component only.

Design principle
----------------
Do NOT optimize purely for win rate.

A strategy with:
    70% win rate + tiny winners + huge losses

can be much worse than:

    48% win rate + large winners + controlled losses.

V5 therefore uses a multi-objective score and keeps a Pareto-style
candidate set instead of blindly selecting the highest return.
"""

from __future__ import annotations

import argparse
import itertools
import json
import math
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Dict, List, Tuple

import numpy as np
import pandas as pd


# ============================================================================
# CONFIGURATION
# ============================================================================

DEFAULT_DATA = (
    "data/historical/xauusd_h1_2024_2026_normalized.csv"
)

DEFAULT_OUTPUT = "backtest_results/weekly_growth_v5"


# V5 strategy families generated by v5_strategy_engine.py
STRATEGY_FAMILIES = [
    "TREND_CONTINUATION",
    "PULLBACK_RETEST",
    "BREAKOUT",
    "LIQUIDITY_REVERSAL",
    "RANGE_MEAN_REVERSION",
    "MOMENTUM_EXPANSION",
]


# Regimes generated by v5_strategy_engine.py
REGIMES = [
    "BULL_TREND",
    "BEAR_TREND",
    "RANGE",
    "VOLATILITY_COMPRESSION",
    "VOLATILITY_EXPANSION",
    "TRANSITION",
]


@dataclass
class Candidate:
    strategy_family: str
    regime: str

    min_signal_score: float
    risk_reward: float
    atr_stop_multiplier: float

    risk_per_trade: float
    max_trades_per_week: int

    # Management
    break_even_r: float
    trailing_start_r: float
    trailing_distance_r: float

    # Results
    trades: int = 0
    wins: int = 0
    losses: int = 0
    gross_profit: float = 0.0
    gross_loss: float = 0.0
    net_profit: float = 0.0
    return_pct: float = 0.0
    max_drawdown_pct: float = 0.0
    profit_factor: float = 0.0
    expectancy_r: float = 0.0
    win_rate: float = 0.0

    # Robustness
    positive_periods: int = 0
    negative_periods: int = 0
    consistency_pct: float = 0.0

    # Final score
    optimization_score: float = -999999.0


# ============================================================================
# DATA LOADING
# ============================================================================

def load_data(path: str) -> pd.DataFrame:
    df = pd.read_csv(path)

    if "timestamp" not in df.columns:
        raise ValueError("Input data must contain timestamp")

    df["timestamp"] = pd.to_datetime(
        df["timestamp"],
        utc=True,
        errors="coerce",
    )

    df = df.dropna(subset=["timestamp"]).copy()

    required = ["open", "high", "low", "close"]

    missing = [c for c in required if c not in df.columns]

    if missing:
        raise ValueError(
            f"Missing required OHLC columns: {missing}"
        )

    for column in required:
        df[column] = pd.to_numeric(
            df[column],
            errors="coerce",
        )

    df = df.dropna(subset=required)

    df = df.sort_values("timestamp")
    df = df.drop_duplicates("timestamp")

    df = df.reset_index(drop=True)

    return df


# ============================================================================
# INDICATORS
# ============================================================================

def calculate_indicators(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()

    close = df["close"]

    df["ema20"] = close.ewm(
        span=20,
        adjust=False,
    ).mean()

    df["ema50"] = close.ewm(
        span=50,
        adjust=False,
    ).mean()

    previous_close = close.shift(1)

    tr = pd.concat(
        [
            df["high"] - df["low"],
            (df["high"] - previous_close).abs(),
            (df["low"] - previous_close).abs(),
        ],
        axis=1,
    ).max(axis=1)

    df["atr14"] = tr.rolling(14).mean()

    df["atr50"] = tr.rolling(50).mean()

    df["atr_ratio"] = (
        df["atr14"] /
        df["atr50"].replace(0, np.nan)
    )

    delta = close.diff()

    gain = delta.clip(lower=0)
    loss = -delta.clip(upper=0)

    avg_gain = gain.rolling(14).mean()
    avg_loss = loss.rolling(14).mean()

    rs = avg_gain / avg_loss.replace(0, np.nan)

    df["rsi14"] = 100 - (
        100 / (1 + rs)
    )

    ema12 = close.ewm(
        span=12,
        adjust=False,
    ).mean()

    ema26 = close.ewm(
        span=26,
        adjust=False,
    ).mean()

    df["macd"] = ema12 - ema26

    df["macd_signal"] = df["macd"].ewm(
        span=9,
        adjust=False,
    ).mean()

    df["macd_hist"] = (
        df["macd"] -
        df["macd_signal"]
    )

    df["range_high"] = (
        df["high"]
        .rolling(20)
        .max()
        .shift(1)
    )

    df["range_low"] = (
        df["low"]
        .rolling(20)
        .min()
        .shift(1)
    )

    return df


# ============================================================================
# REGIME DETECTION
# ============================================================================

def detect_regime(row: pd.Series) -> str:
    ema20 = row["ema20"]
    ema50 = row["ema50"]
    atr_ratio = row["atr_ratio"]
    close = row["close"]

    if any(
        pd.isna(x)
        for x in [
            ema20,
            ema50,
            atr_ratio,
            close,
        ]
    ):
        return "TRANSITION"

    distance = abs(ema20 - ema50) / max(
        abs(close),
        1e-9,
    )

    if atr_ratio < 0.70:
        return "VOLATILITY_COMPRESSION"

    if atr_ratio > 1.50:
        return "VOLATILITY_EXPANSION"

    if (
        ema20 > ema50
        and close > ema50
        and distance > 0.001
    ):
        return "BULL_TREND"

    if (
        ema20 < ema50
        and close < ema50
        and distance > 0.001
    ):
        return "BEAR_TREND"

    if distance < 0.001:
        return "RANGE"

    return "TRANSITION"


# ============================================================================
# SIGNAL GENERATION
# ============================================================================

def calculate_signal_score(
    row: pd.Series,
    family: str,
    regime: str,
) -> Tuple[str, float]:
    """
    Produce a normalized V5 research signal.

    BUY = +score
    SELL = -score
    WAIT = 0
    """

    if regime != detect_regime(row):
        return "WAIT", 0.0

    close = row["close"]
    ema20 = row["ema20"]
    ema50 = row["ema50"]
    rsi = row["rsi14"]
    macd = row["macd"]
    macd_signal = row["macd_signal"]

    if any(
        pd.isna(x)
        for x in [
            close,
            ema20,
            ema50,
            rsi,
            macd,
            macd_signal,
        ]
    ):
        return "WAIT", 0.0

    buy = 0.0
    sell = 0.0

    # ------------------------------------------------------------------
    # TREND CONTINUATION
    # ------------------------------------------------------------------

    if family == "TREND_CONTINUATION":

        if regime == "BULL_TREND":
            buy += 30

            if close > ema20:
                buy += 20

            if macd > macd_signal:
                buy += 20

            if 52 <= rsi <= 72:
                buy += 20

            return "BUY", min(buy, 100)

        if regime == "BEAR_TREND":
            sell += 30

            if close < ema20:
                sell += 20

            if macd < macd_signal:
                sell += 20

            if 28 <= rsi <= 48:
                sell += 20

            return "SELL", min(sell, 100)

    # ------------------------------------------------------------------
    # PULLBACK / RETEST
    # ------------------------------------------------------------------

    if family == "PULLBACK_RETEST":

        if regime == "BULL_TREND":

            if close >= ema20:
                buy += 25

            if close > ema50:
                buy += 25

            if macd >= macd_signal:
                buy += 20

            if 45 <= rsi <= 65:
                buy += 20

            return "BUY", min(buy, 100)

        if regime == "BEAR_TREND":

            if close <= ema20:
                sell += 25

            if close < ema50:
                sell += 25

            if macd <= macd_signal:
                sell += 20

            if 35 <= rsi <= 55:
                sell += 20

            return "SELL", min(sell, 100)

    # ------------------------------------------------------------------
    # BREAKOUT
    # ------------------------------------------------------------------

    if family == "BREAKOUT":

        range_high = row.get("range_high")
        range_low = row.get("range_low")

        if pd.notna(range_high) and close > range_high:
            buy += 50

            if macd > macd_signal:
                buy += 20

            if rsi > 55:
                buy += 20

            return "BUY", min(buy, 100)

        if pd.notna(range_low) and close < range_low:
            sell += 50

            if macd < macd_signal:
                sell += 20

            if rsi < 45:
                sell += 20

            return "SELL", min(sell, 100)

    # ------------------------------------------------------------------
    # LIQUIDITY REVERSAL
    # ------------------------------------------------------------------

    if family == "LIQUIDITY_REVERSAL":

        previous_low = row.get("range_low")
        previous_high = row.get("range_high")

        if pd.notna(previous_low):

            if (
                row["low"] < previous_low
                and close > previous_low
            ):
                buy += 55

                if rsi < 45:
                    buy += 20

                if macd > macd_signal:
                    buy += 15

                return "BUY", min(buy, 100)

        if pd.notna(previous_high):

            if (
                row["high"] > previous_high
                and close < previous_high
            ):
                sell += 55

                if rsi > 55:
                    sell += 20

                if macd < macd_signal:
                    sell += 15

                return "SELL", min(sell, 100)

    # ------------------------------------------------------------------
    # RANGE MEAN REVERSION
    # ------------------------------------------------------------------

    if family == "RANGE_MEAN_REVERSION":

        if regime != "RANGE":
            return "WAIT", 0.0

        range_high = row.get("range_high")
        range_low = row.get("range_low")

        if (
            pd.notna(range_low)
            and close <= range_low * 1.001
            and rsi < 40
        ):
            buy = 70

            if macd > macd_signal:
                buy += 20

            return "BUY", min(buy, 100)

        if (
            pd.notna(range_high)
            and close >= range_high * 0.999
            and rsi > 60
        ):
            sell = 70

            if macd < macd_signal:
                sell += 20

            return "SELL", min(sell, 100)

    # ------------------------------------------------------------------
    # MOMENTUM EXPANSION
    # ------------------------------------------------------------------

    if family == "MOMENTUM_EXPANSION":

        if regime != "VOLATILITY_EXPANSION":
            return "WAIT", 0.0

        if (
            close > ema20
            and ema20 > ema50
            and macd > macd_signal
            and rsi > 55
        ):
            return "BUY", 90.0

        if (
            close < ema20
            and ema20 < ema50
            and macd < macd_signal
            and rsi < 45
        ):
            return "SELL", 90.0

    return "WAIT", 0.0


# ============================================================================
# TRADE SIMULATOR
# ============================================================================

def simulate_candidate(
    df: pd.DataFrame,
    family: str,
    regime: str,
    min_signal_score: float,
    risk_reward: float,
    atr_stop_multiplier: float,
    risk_per_trade: float,
    max_trades_per_week: int,
    break_even_r: float,
    trailing_start_r: float,
    trailing_distance_r: float,
    starting_balance: float = 1000.0,
) -> Dict:

    balance = starting_balance
    peak_balance = balance

    trades = []

    weekly_counts: Dict[str, int] = {}

    position = None

    for i in range(60, len(df)):

        row = df.iloc[i]

        timestamp = row["timestamp"]

        week_key = (
            timestamp
            .strftime("%Y-%W")
        )

        signal, score = calculate_signal_score(
            row,
            family,
            regime,
        )

        # --------------------------------------------------------------
        # MANAGE OPEN POSITION
        # --------------------------------------------------------------

        if position is not None:

            direction = position["direction"]
            entry = position["entry"]
            stop = position["stop"]
            target = position["target"]
            risk = position["risk"]

            high = row["high"]
            low = row["low"]

            # Break-even
            if direction == "BUY":

                if high >= entry + risk * break_even_r:
                    position["stop"] = max(
                        position["stop"],
                        entry,
                    )

                if high >= (
                    entry +
                    risk * trailing_start_r
                ):
                    new_stop = (
                        high -
                        risk * trailing_distance_r
                    )

                    position["stop"] = max(
                        position["stop"],
                        new_stop,
                    )

                if low <= position["stop"]:

                    exit_price = position["stop"]

                    r_multiple = (
                        exit_price - entry
                    ) / risk

                    pnl = (
                        balance *
                        risk_per_trade *
                        r_multiple
                    )

                    balance += pnl

                    trades.append(
                        {
                            "timestamp": timestamp,
                            "family": family,
                            "regime": regime,
                            "direction": direction,
                            "entry": entry,
                            "exit": exit_price,
                            "r": r_multiple,
                            "pnl": pnl,
                            "reason": "SL_OR_TRAILING",
                        }
                    )

                    position = None

                elif high >= target:

                    exit_price = target

                    r_multiple = risk_reward

                    pnl = (
                        balance *
                        risk_per_trade *
                        r_multiple
                    )

                    balance += pnl

                    trades.append(
                        {
                            "timestamp": timestamp,
                            "family": family,
                            "regime": regime,
                            "direction": direction,
                            "entry": entry,
                            "exit": exit_price,
                            "r": r_multiple,
                            "pnl": pnl,
                            "reason": "TP",
                        }
                    )

                    position = None

            else:

                if low <= entry - risk * break_even_r:
                    position["stop"] = min(
                        position["stop"],
                        entry,
                    )

                if low <= (
                    entry -
                    risk * trailing_start_r
                ):
                    new_stop = (
                        low +
                        risk * trailing_distance_r
                    )

                    position["stop"] = min(
                        position["stop"],
                        new_stop,
                    )

                if high >= position["stop"]:

                    exit_price = position["stop"]

                    r_multiple = (
                        entry - exit_price
                    ) / risk

                    pnl = (
                        balance *
                        risk_per_trade *
                        r_multiple
                    )

                    balance += pnl

                    trades.append(
                        {
                            "timestamp": timestamp,
                            "family": family,
                            "regime": regime,
                            "direction": direction,
                            "entry": entry,
                            "exit": exit_price,
                            "r": r_multiple,
                            "pnl": pnl,
                            "reason": "SL_OR_TRAILING",
                        }
                    )

                    position = None

                elif low <= target:

                    exit_price = target

                    r_multiple = risk_reward

                    pnl = (
                        balance *
                        risk_per_trade *
                        r_multiple
                    )

                    balance += pnl

                    trades.append(
                        {
                            "timestamp": timestamp,
                            "family": family,
                            "regime": regime,
                            "direction": direction,
                            "entry": entry,
                            "exit": exit_price,
                            "r": r_multiple,
                            "pnl": pnl,
                            "reason": "TP",
                        }
                    )

                    position = None

        # --------------------------------------------------------------
        # OPEN NEW POSITION
        # --------------------------------------------------------------

        if position is None:

            count = weekly_counts.get(
                week_key,
                0,
            )

            if count >= max_trades_per_week:
                continue

            if score < min_signal_score:
                continue

            if signal not in {"BUY", "SELL"}:
                continue

            atr = row["atr14"]

            if pd.isna(atr) or atr <= 0:
                continue

            entry = row["close"]

            risk_distance = (
                atr *
                atr_stop_multiplier
            )

            if risk_distance <= 0:
                continue

            if signal == "BUY":

                stop = (
                    entry -
                    risk_distance
                )

                target = (
                    entry +
                    risk_distance *
                    risk_reward
                )

            else:

                stop = (
                    entry +
                    risk_distance
                )

                target = (
                    entry -
                    risk_distance *
                    risk_reward
                )

            position = {
                "direction": signal,
                "entry": entry,
                "stop": stop,
                "target": target,
                "risk": risk_distance,
            }

            weekly_counts[week_key] = (
                count + 1
            )

    # ------------------------------------------------------------------
    # METRICS
    # ------------------------------------------------------------------

    if not trades:

        return {
            "trades": 0,
            "wins": 0,
            "losses": 0,
            "gross_profit": 0.0,
            "gross_loss": 0.0,
            "net_profit": 0.0,
            "return_pct": 0.0,
            "max_drawdown_pct": 0.0,
            "profit_factor": 0.0,
            "expectancy_r": 0.0,
            "win_rate": 0.0,
            "positive_periods": 0,
            "negative_periods": 0,
            "consistency_pct": 0.0,
            "trade_records": [],
        }

    trade_df = pd.DataFrame(trades)

    wins = int(
        (trade_df["pnl"] > 0).sum()
    )

    losses = int(
        (trade_df["pnl"] < 0).sum()
    )

    gross_profit = float(
        trade_df.loc[
            trade_df["pnl"] > 0,
            "pnl",
        ].sum()
    )

    gross_loss = float(
        trade_df.loc[
            trade_df["pnl"] < 0,
            "pnl",
        ].sum()
    )

    net_profit = float(
        trade_df["pnl"].sum()
    )

    return_pct = (
        (balance - starting_balance) /
        starting_balance *
        100
    )

    equity = (
        starting_balance +
        trade_df["pnl"].cumsum()
    )

    running_peak = equity.cummax()

    drawdown = (
        running_peak - equity
    ) / running_peak * 100

    max_drawdown_pct = float(
        drawdown.max()
    )

    if gross_loss < 0:
        profit_factor = (
            gross_profit /
            abs(gross_loss)
        )
    else:
        profit_factor = 999.0

    expectancy_r = float(
        trade_df["r"].mean()
    )

    win_rate = (
        wins /
        len(trade_df) *
        100
    )

    # Monthly consistency
    trade_df["period"] = (
        pd.to_datetime(
            trade_df["timestamp"],
            utc=True,
        )
        .dt.to_period("M")
        .astype(str)
    )

    period_results = (
        trade_df
        .groupby("period")["pnl"]
        .sum()
    )

    positive_periods = int(
        (period_results > 0).sum()
    )

    negative_periods = int(
        (period_results < 0).sum()
    )

    total_periods = (
        positive_periods +
        negative_periods
    )

    consistency_pct = (
        positive_periods /
        total_periods *
        100
        if total_periods
        else 0.0
    )

    return {
        "trades": len(trade_df),
        "wins": wins,
        "losses": losses,
        "gross_profit": gross_profit,
        "gross_loss": gross_loss,
        "net_profit": net_profit,
        "return_pct": return_pct,
        "max_drawdown_pct": max_drawdown_pct,
        "profit_factor": profit_factor,
        "expectancy_r": expectancy_r,
        "win_rate": win_rate,
        "positive_periods": positive_periods,
        "negative_periods": negative_periods,
        "consistency_pct": consistency_pct,
        "trade_records": trades,
    }


# ============================================================================
# OPTIMIZATION OBJECTIVE
# ============================================================================

def optimization_score(metrics: Dict) -> float:

    trades = metrics["trades"]

    if trades < 20:
        return -10000.0

    pf = min(
        metrics["profit_factor"],
        5.0,
    )

    ret = metrics["return_pct"]

    dd = metrics["max_drawdown_pct"]

    expectancy = metrics["expectancy_r"]

    consistency = (
        metrics["consistency_pct"]
    )

    # Growth reward
    growth_component = (
        np.sign(ret) *
        math.log1p(abs(ret)) *
        12.0
    )

    # Profit factor reward
    pf_component = (
        max(pf - 1.0, -1.0) *
        25.0
    )

    # Expectancy
    expectancy_component = (
        np.clip(
            expectancy,
            -2.0,
            2.0,
        ) *
        20.0
    )

    # Consistency
    consistency_component = (
        consistency *
        0.30
    )

    # Drawdown penalty
    drawdown_penalty = (
        max(dd - 10.0, 0.0) *
        2.5
    )

    # Penalize very small samples.
    sample_bonus = min(
        math.log1p(trades) * 2.0,
        15.0,
    )

    score = (
        growth_component
        + pf_component
        + expectancy_component
        + consistency_component
        + sample_bonus
        - drawdown_penalty
    )

    return float(score)


# ============================================================================
# PARAMETER GRID
# ============================================================================

def build_grid() -> List[Dict]:

    grid = {
        "strategy_family": STRATEGY_FAMILIES,

        "regime": REGIMES,

        "min_signal_score": [
            55,
            60,
            65,
            70,
            75,
        ],

        "risk_reward": [
            1.5,
            2.0,
            2.5,
            3.0,
            3.5,
            4.0,
        ],

        "atr_stop_multiplier": [
            0.8,
            1.0,
            1.2,
            1.4,
            1.6,
        ],

        "risk_per_trade": [
            0.01,
            0.015,
            0.02,
            0.025,
        ],

        "max_trades_per_week": [
            3,
            5,
            8,
        ],

        "break_even_r": [
            0.8,
            1.0,
        ],

        "trailing_start_r": [
            1.5,
            2.0,
            2.5,
        ],

        "trailing_distance_r": [
            0.75,
            1.0,
            1.25,
        ],
    }

    keys = list(grid.keys())

    combinations = []

    for values in itertools.product(
        *[
            grid[key]
            for key in keys
        ]
    ):
        combinations.append(
            dict(
                zip(keys, values)
            )
        )

    return combinations


# ============================================================================
# WALK-FORWARD DATA SPLIT
# ============================================================================

def split_walk_forward(
    df: pd.DataFrame,
) -> Dict[str, pd.DataFrame]:

    years = (
        df["timestamp"]
        .dt.year
    )

    return {
        "development": df[
            years == 2024
        ].copy(),

        "selection": df[
            years == 2025
        ].copy(),

        "holdout": df[
            years >= 2026
        ].copy(),

        "full": df.copy(),
    }


# ============================================================================
# CANDIDATE EVALUATION
# ============================================================================

def evaluate_candidate(
    dataset: pd.DataFrame,
    params: Dict,
) -> Candidate:

    metrics = simulate_candidate(
        dataset,
        family=params["strategy_family"],
        regime=params["regime"],
        min_signal_score=params["min_signal_score"],
        risk_reward=params["risk_reward"],
        atr_stop_multiplier=params[
            "atr_stop_multiplier"
        ],
        risk_per_trade=params[
            "risk_per_trade"
        ],
        max_trades_per_week=params[
            "max_trades_per_week"
        ],
        break_even_r=params[
            "break_even_r"
        ],
        trailing_start_r=params[
            "trailing_start_r"
        ],
        trailing_distance_r=params[
            "trailing_distance_r"
        ],
    )

    score = optimization_score(
        metrics
    )

    return Candidate(
        **params,
        trades=metrics["trades"],
        wins=metrics["wins"],
        losses=metrics["losses"],
        gross_profit=metrics["gross_profit"],
        gross_loss=metrics["gross_loss"],
        net_profit=metrics["net_profit"],
        return_pct=metrics["return_pct"],
        max_drawdown_pct=metrics[
            "max_drawdown_pct"
        ],
        profit_factor=metrics[
            "profit_factor"
        ],
        expectancy_r=metrics[
            "expectancy_r"
        ],
        win_rate=metrics[
            "win_rate"
        ],
        positive_periods=metrics[
            "positive_periods"
        ],
        negative_periods=metrics[
            "negative_periods"
        ],
        consistency_pct=metrics[
            "consistency_pct"
        ],
        optimization_score=score,
    )


# ============================================================================
# PARETO FILTER
# ============================================================================

def pareto_frontier(
    candidates: List[Candidate],
) -> List[Candidate]:

    frontier = []

    for candidate in candidates:

        dominated = False

        for other in candidates:

            if other is candidate:
                continue

            other_better_or_equal = (
                other.return_pct
                >= candidate.return_pct
                and
                other.profit_factor
                >= candidate.profit_factor
                and
                other.expectancy_r
                >= candidate.expectancy_r
                and
                other.consistency_pct
                >= candidate.consistency_pct
                and
                other.max_drawdown_pct
                <= candidate.max_drawdown_pct
            )

            strictly_better = (
                other.return_pct
                > candidate.return_pct
                or
                other.profit_factor
                > candidate.profit_factor
                or
                other.expectancy_r
                > candidate.expectancy_r
                or
                other.consistency_pct
                > candidate.consistency_pct
                or
                other.max_drawdown_pct
                < candidate.max_drawdown_pct
            )

            if (
                other_better_or_equal
                and strictly_better
            ):
                dominated = True
                break

        if not dominated:
            frontier.append(candidate)

    return frontier


# ============================================================================
# MAIN RESEARCH
# ============================================================================

def run_optimizer(
    data_path: str,
    output_dir: str,
    max_candidates: int | None = None,
) -> None:

    output = Path(output_dir)
    output.mkdir(
        parents=True,
        exist_ok=True,
    )

    print("=" * 80)
    print("RAYMOND V2.8 - V5 OPTIMIZER")
    print("=" * 80)

    df = load_data(data_path)

    df = calculate_indicators(df)

    df["regime"] = df.apply(
        detect_regime,
        axis=1,
    )

    datasets = split_walk_forward(df)

    print(
        f"Rows loaded: {len(df):,}"
    )

    print(
        f"2024 development: "
        f"{len(datasets['development']):,}"
    )

    print(
        f"2025 selection: "
        f"{len(datasets['selection']):,}"
    )

    print(
        f"2026 holdout: "
        f"{len(datasets['holdout']):,}"
    )

    grid = build_grid()

    if max_candidates:
        grid = grid[:max_candidates]

    print(
        f"Parameter combinations: "
        f"{len(grid):,}"
    )

    development_candidates = []

    # --------------------------------------------------------------
    # DEVELOPMENT
    # --------------------------------------------------------------

    print()
    print("PHASE 1: DEVELOPMENT")
    print("-" * 80)

    for index, params in enumerate(
        grid,
        start=1,
    ):

        candidate = evaluate_candidate(
            datasets["development"],
            params,
        )

        development_candidates.append(
            candidate
        )

        if index % 100 == 0:
            print(
                f"Evaluated "
                f"{index:,}/"
                f"{len(grid):,}"
            )

    development_candidates.sort(
        key=lambda x:
        x.optimization_score,
        reverse=True,
    )

    top_development = (
        development_candidates[:50]
    )

    # --------------------------------------------------------------
    # SELECTION
    # --------------------------------------------------------------

    print()
    print("PHASE 2: SELECTION")
    print("-" * 80)

    selection_candidates = []

    for candidate in top_development:

        params = {
            "strategy_family":
                candidate.strategy_family,
            "regime":
                candidate.regime,
            "min_signal_score":
                candidate.min_signal_score,
            "risk_reward":
                candidate.risk_reward,
            "atr_stop_multiplier":
                candidate.atr_stop_multiplier,
            "risk_per_trade":
                candidate.risk_per_trade,
            "max_trades_per_week":
                candidate.max_trades_per_week,
            "break_even_r":
                candidate.break_even_r,
            "trailing_start_r":
                candidate.trailing_start_r,
            "trailing_distance_r":
                candidate.trailing_distance_r,
        }

        selection_candidate = (
            evaluate_candidate(
                datasets["selection"],
                params,
            )
        )

        selection_candidates.append(
            selection_candidate
        )

    selection_candidates.sort(
        key=lambda x:
        x.optimization_score,
        reverse=True,
    )

    top_selection = (
        selection_candidates[:20]
    )

    # --------------------------------------------------------------
    # HOLDOUT
    # --------------------------------------------------------------

    print()
    print("PHASE 3: UNSEEN HOLDOUT")
    print("-" * 80)

    holdout_candidates = []

    for candidate in top_selection:

        params = {
            "strategy_family":
                candidate.strategy_family,
            "regime":
                candidate.regime,
            "min_signal_score":
                candidate.min_signal_score,
            "risk_reward":
                candidate.risk_reward,
            "atr_stop_multiplier":
                candidate.atr_stop_multiplier,
            "risk_per_trade":
                candidate.risk_per_trade,
            "max_trades_per_week":
                candidate.max_trades_per_week,
            "break_even_r":
                candidate.break_even_r,
            "trailing_start_r":
                candidate.trailing_start_r,
            "trailing_distance_r":
                candidate.trailing_distance_r,
        }

        holdout_candidate = (
            evaluate_candidate(
                datasets["holdout"],
                params,
            )
        )

        holdout_candidates.append(
            holdout_candidate
        )

    holdout_candidates.sort(
        key=lambda x:
        x.optimization_score,
        reverse=True,
    )

    # --------------------------------------------------------------
    # PARETO FRONTIER
    # --------------------------------------------------------------

    frontier = pareto_frontier(
        holdout_candidates
    )

    frontier.sort(
        key=lambda x:
        x.optimization_score,
        reverse=True,
    )

    # --------------------------------------------------------------
    # FULL PERIOD
    # --------------------------------------------------------------

    print()
    print("PHASE 4: FULL PERIOD")
    print("-" * 80)

    full_candidates = []

    for candidate in frontier:

        params = {
            "strategy_family":
                candidate.strategy_family,
            "regime":
                candidate.regime,
            "min_signal_score":
                candidate.min_signal_score,
            "risk_reward":
                candidate.risk_reward,
            "atr_stop_multiplier":
                candidate.atr_stop_multiplier,
            "risk_per_trade":
                candidate.risk_per_trade,
            "max_trades_per_week":
                candidate.max_trades_per_week,
            "break_even_r":
                candidate.break_even_r,
            "trailing_start_r":
                candidate.trailing_start_r,
            "trailing_distance_r":
                candidate.trailing_distance_r,
        }

        full_candidate = (
            evaluate_candidate(
                datasets["full"],
                params,
            )
        )

        full_candidates.append(
            full_candidate
        )

    full_candidates.sort(
        key=lambda x:
        x.optimization_score,
        reverse=True,
    )

    # =========================================================================
    # SAVE RESULTS
    # =========================================================================

    def dataframe_from_candidates(
        values: List[Candidate],
    ) -> pd.DataFrame:

        return pd.DataFrame(
            [
                asdict(candidate)
                for candidate in values
            ]
        )

    dataframe_from_candidates(
        development_candidates
    ).to_csv(
        output /
        "v5_development_candidates.csv",
        index=False,
    )

    dataframe_from_candidates(
        selection_candidates
    ).to_csv(
        output /
        "v5_selection_candidates.csv",
        index=False,
    )

    dataframe_from_candidates(
        holdout_candidates
    ).to_csv(
        output /
        "v5_holdout_candidates.csv",
        index=False,
    )

    dataframe_from_candidates(
        frontier
    ).to_csv(
        output /
        "v5_pareto_frontier.csv",
        index=False,
    )

    dataframe_from_candidates(
        full_candidates
    ).to_csv(
        output /
        "v5_full_period_candidates.csv",
        index=False,
    )

    # =========================================================================
    # BEST CANDIDATE
    # =========================================================================

    best = (
        full_candidates[0]
        if full_candidates
        else None
    )

    if best:

        with open(
            output /
            "v5_selected_config.json",
            "w",
            encoding="utf-8",
        ) as file:

            json.dump(
                asdict(best),
                file,
                indent=2,
                default=str,
            )

    # =========================================================================
    # SUMMARY
    # =========================================================================

    lines = []

    lines.append(
        "RAYMOND V2.8 V5 OPTIMIZER"
    )

    lines.append(
        "=" * 80
    )

    lines.append(
        f"Rows: {len(df):,}"
    )

    lines.append(
        f"Grid combinations: {len(grid):,}"
    )

    lines.append(
        ""
    )

    lines.append(
        "OBJECTIVE"
    )

    lines.append(
        "---------"
    )

    lines.append(
        "Multi-objective research score:"
    )

    lines.append(
        "- compounded return"
    )

    lines.append(
        "- profit factor"
    )

    lines.append(
        "- expectancy"
    )

    lines.append(
        "- consistency"
    )

    lines.append(
        "- sample size"
    )

    lines.append(
        "- maximum drawdown penalty"
    )

    lines.append(
        ""
    )

    if best:

        lines.append(
            "BEST FULL-PERIOD CANDIDATE"
        )

        lines.append(
            "--------------------------"
        )

        lines.append(
            f"Strategy: "
            f"{best.strategy_family}"
        )

        lines.append(
            f"Regime: "
            f"{best.regime}"
        )

        lines.append(
            f"Minimum signal score: "
            f"{best.min_signal_score}"
        )

        lines.append(
            f"Risk/reward: "
            f"{best.risk_reward}"
        )

        lines.append(
            f"ATR stop multiplier: "
            f"{best.atr_stop_multiplier}"
        )

        lines.append(
            f"Risk/trade: "
            f"{best.risk_per_trade:.2%}"
        )

        lines.append(
            f"Trades: {best.trades}"
        )

        lines.append(
            f"Win rate: "
            f"{best.win_rate:.2f}%"
        )

        lines.append(
            f"Return: "
            f"{best.return_pct:.2f}%"
        )

        lines.append(
            f"Profit factor: "
            f"{best.profit_factor:.3f}"
        )

        lines.append(
            f"Expectancy R: "
            f"{best.expectancy_r:.4f}"
        )

        lines.append(
            f"Max drawdown: "
            f"{best.max_drawdown_pct:.2f}%"
        )

        lines.append(
            f"Consistency: "
            f"{best.consistency_pct:.2f}%"
        )

        lines.append(
            f"Optimization score: "
            f"{best.optimization_score:.3f}"
        )

    else:

        lines.append(
            "No valid candidate found."
        )

    lines.append(
        ""
    )

    lines.append(
        f"Pareto candidates: "
        f"{len(frontier)}"
    )

    lines.append(
        ""
    )

    lines.append(
        "IMPORTANT:"
    )

    lines.append(
        "The holdout period is not used to create"
    )

    lines.append(
        "the optimization grid. It is used to test"
    )

    lines.append(
        "whether the selected research ideas survive"
    )

    lines.append(
        "unseen data."
    )

    with open(
        output / "summary.txt",
        "w",
        encoding="utf-8",
    ) as file:

        file.write(
            "\n".join(lines)
        )

    # =========================================================================
    # DIAGNOSTICS
    # =========================================================================

    diagnostics = {
        "status": "completed",
        "rows": len(df),
        "grid_size": len(grid),
        "development_candidates":
            len(development_candidates),
        "selection_candidates":
            len(selection_candidates),
        "holdout_candidates":
            len(holdout_candidates),
        "pareto_candidates":
            len(frontier),
        "full_candidates":
            len(full_candidates),
        "strategy_families":
            STRATEGY_FAMILIES,
        "regimes":
            REGIMES,
    }

    with open(
        output /
        "v5_optimizer_diagnostics.json",
        "w",
        encoding="utf-8",
    ) as file:

        json.dump(
            diagnostics,
            file,
            indent=2,
        )

    print()
    print("=" * 80)
    print("V5 OPTIMIZATION COMPLETE")
    print("=" * 80)

    if best:

        print(
            f"Best strategy: "
            f"{best.strategy_family}"
        )

        print(
            f"Regime: {best.regime}"
        )

        print(
            f"Return: "
            f"{best.return_pct:.2f}%"
        )

        print(
            f"Win rate: "
            f"{best.win_rate:.2f}%"
        )

        print(
            f"Profit factor: "
            f"{best.profit_factor:.3f}"
        )

        print(
            f"Max DD: "
            f"{best.max_drawdown_pct:.2f}%"
        )

        print(
            f"Pareto candidates: "
            f"{len(frontier)}"
        )


# ============================================================================
# CLI
# ============================================================================

def main() -> None:

    parser = argparse.ArgumentParser(
        description=(
            "Raymond V2.8 V5 research optimizer"
        )
    )

    parser.add_argument(
        "--data",
        default=DEFAULT_DATA,
    )

    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
    )

    parser.add_argument(
        "--max-candidates",
        type=int,
        default=None,
        help=(
            "Optional limit for development "
            "grid size."
        ),
    )

    args = parser.parse_args()

    run_optimizer(
        data_path=args.data,
        output_dir=args.output,
        max_candidates=args.max_candidates,
    )


if __name__ == "__main__":
    main()
